apiVersion: apps/v1
kind: Deployment
metadata:
  name: semantic-search-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: semantic-search-server
  template:
    metadata:
      labels:
        app: semantic-search-server
    spec:
      containers:
      - name: search-server
        image: tuandung12092002/semantic-search-server:latest
        ports:
        - containerPort: 8000
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: semantic-search-secrets
              key: openai-api-key
        - name: WEAVIATE_URL
          value: "http://weaviate.weaviate.svc.cluster.local:8080"
        - name: WEAVIATE_API_KEY
          valueFrom:
            secretKeyRef:
              name: semantic-search-secrets
              key: weaviate-api-key
        - name: API_HOST
          value: "0.0.0.0"
        - name: API_PORT
          value: "8000"
        - name: LOG_LEVEL
          value: "INFO"
        - name: LOAD_SAMPLE_DATA
          value: "true"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: semantic-search-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: semantic-search-demo
  template:
    metadata:
      labels:
        app: semantic-search-demo
    spec:
      containers:
      - name: demo-app
        image: tuandung12092002/semantic-search-demo:latest
        ports:
        - containerPort: 8501
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: semantic-search-secrets
              key: openai-api-key
        - name: API_URL
          value: "http://semantic-search-server:8000"
        - name: DEMO_PORT
          value: "8501"
        - name: LOG_LEVEL
          value: "INFO"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /
            port: 8501
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8501
          initialDelaySeconds: 15
          periodSeconds: 20 