name: Lint and Test

on:
  push:
    branches: [ main, master ]
    paths:
      - '**.py'
      - 'requirements*.txt'
  pull_request:
    branches: [ main, master ]
    paths:
      - '**.py'
      - 'requirements*.txt'
  workflow_dispatch:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint pytest pytest-cov black isort mypy
          
      - name: Check formatting with Black
        run: |
          black --check --diff src/
          
      - name: Check imports with isort
        run: |
          isort --check --diff src/
          
      - name: Check types with mypy
        run: |
          mypy src/
          
      - name: Run pylint
        run: |
          pylint src/ --disable=C0111,C0103
          
      - name: Run tests with pytest
        run: |
          pytest src/tests/ --cov=src/ --cov-report=xml
          
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: false 